name: reddit_ui_challenge
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  path_provider: ^2.0.8
  image_picker: ^1.0.4
  image_picker_ios: ^0.8.5+6
  flutter_inappwebview: ^5.7.1
  url_launcher: ^6.1.2
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  share_plus: ^6.3.0
  expandable_bottom_sheet: ^1.1.1+1
  intl: ^0.18.0
  flutter_svg: ^1.1.6
  easy_localization: ^3.0.3
  provider: ^6.0.5
  get_it: ^7.6.4
  loader_overlay: ^2.3.2
  either_dart: ^1.0.0
  shimmer: ^3.0.0
  lottie: ^2.6.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  animated_flip_counter: ^0.2.6
  video_player: ^2.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/image/
    - assets/translations/
    - assets/svg/
    - assets/animations/

  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/font/Cairo/Cairo-Regular.ttf
  #         weight: 400
  #       - asset: assets/font/Cairo/Cairo-SemiBold.ttf
  #         weight: 500
  #       - asset: assets/font/Cairo/Cairo-Bold.ttf
  #         weight: 700
  #       - asset: assets/font/Cairo/Cairo-Black.ttf
  #         weight: 900

